Add forbiden_message hook

diff --git a/GitMate/hooks/pre-commit b/GitMate/hooks/pre-commit
--- a/GitMate/hooks/pre-commit
+++ b/GitMate/hooks/pre-commit
@@ -23,24 +23,23 @@ exec 1>&2
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
- # Note that the use of brackets around a tr range is ok here, (it's
- # even required, for portability to Solaris 10's /usr/bin/tr), since
- # the square bracket bytes happen to fall in the designated range.
- test $(git diff --cached --name-only --diff-filter=A -z $against |
-   LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+    # Note that the use of brackets around a tr range is ok here, (it's
+    # even required, for portability to Solaris 10's /usr/bin/tr), since
+    # the square bracket bytes happen to fall in the designated range.
+    test $(git diff --cached --name-only --diff-filter=A -z $against | LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
- cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
-
-This can cause problems if you want to work with people on other platforms.
-
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
- exit 1
+    # Message to the user
+    echo "Error: Attempt to add a non-ASCII file name."
+    echo "This can cause problems if you want to work with people on other platforms."
+    echo "To be portable it is advisable to rename the file ..."
+    # Ask the user to fix the error
+    read -p "Do you want to proceed and add the file? (y/n) " answer < /dev/tty
+    # Check the answer
+    if [ "$answer" != "y" ]
+    then
+        # Exit with a non-zero status
+        exit 1
+    fi
 fi
 
 # Get the list of files that are being committed
